apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mymysql
spec:
  selector:
    matchLabels:
      app: mymysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mymysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        ports:
        - containerPort: 3306
