apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mynodejs
spec:
  selector:
    matchLabels:
      app: mynodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: mynodejs
    spec:
      containers:
      - name: mynodejs
        image: docker.io/rajbhaveshraj/devopstest:nodejsappV1.1
        ports:
        - containerPort: 8080
        env:
        - name: GET_HOSTS_FROM
          value: dns
